-- Crawler Agent v13.6 MySQL RAG schema
-- Target: MySQL 8.4 LTS / InnoDB / utf8mb4

CREATE TABLE IF NOT EXISTS rag_memory (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    memory_key BINARY(32) NOT NULL,
    memory_type VARCHAR(32) NOT NULL,
    status VARCHAR(24) NOT NULL DEFAULT 'active',
    source_kind VARCHAR(24) NOT NULL,
    domain VARCHAR(255) NOT NULL,
    route_template VARCHAR(512) NOT NULL DEFAULT '',
    route_hash BINARY(32) NOT NULL,
    task_type VARCHAR(64) NOT NULL DEFAULT '',
    entity_type VARCHAR(64) NOT NULL DEFAULT '',
    collection_type VARCHAR(64) NOT NULL DEFAULT '',
    data_source VARCHAR(32) NOT NULL DEFAULT '',
    summary TEXT NOT NULL,
    searchable_text LONGTEXT NOT NULL,
    facts JSON NOT NULL,
    metrics JSON NOT NULL,
    reliability_score DECIMAL(6,5) NOT NULL DEFAULT 0.50000,
    confidence_score DECIMAL(6,5) NOT NULL DEFAULT 0.50000,
    successful_runs INT UNSIGNED NOT NULL DEFAULT 0,
    failed_runs INT UNSIGNED NOT NULL DEFAULT 0,
    complete_runs INT UNSIGNED NOT NULL DEFAULT 0,
    partial_runs INT UNSIGNED NOT NULL DEFAULT 0,
    retrieval_count INT UNSIGNED NOT NULL DEFAULT 0,
    selected_count INT UNSIGNED NOT NULL DEFAULT 0,
    validation_success_count INT UNSIGNED NOT NULL DEFAULT 0,
    validation_failure_count INT UNSIGNED NOT NULL DEFAULT 0,
    contribution_count INT UNSIGNED NOT NULL DEFAULT 0,
    last_verified_at DATETIME(6) NULL,
    last_failed_at DATETIME(6) NULL,
    fresh_until DATETIME(6) NULL,
    schema_version SMALLINT UNSIGNED NOT NULL,
    agent_build VARCHAR(128) NOT NULL DEFAULT '',
    created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    PRIMARY KEY (id),
    UNIQUE KEY uk_memory_key (memory_key),
    KEY idx_domain_task (domain, task_type, memory_type, status),
    KEY idx_route (domain, route_hash, task_type, status),
    KEY idx_freshness (status, fresh_until, reliability_score),
    FULLTEXT KEY ft_memory_text (summary, searchable_text) WITH PARSER ngram,
    CONSTRAINT chk_rag_memory_facts CHECK (JSON_VALID(facts)),
    CONSTRAINT chk_rag_memory_metrics CHECK (JSON_VALID(metrics))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS rag_strategy_endpoint (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    memory_id BIGINT UNSIGNED NOT NULL,
    endpoint_key BINARY(32) NOT NULL,
    endpoint_template TEXT NOT NULL,
    endpoint_family VARCHAR(255) NOT NULL,
    http_method VARCHAR(12) NOT NULL DEFAULT 'GET',
    source_kind VARCHAR(24) NOT NULL,
    verified TINYINT(1) NOT NULL DEFAULT 0,
    request_template JSON NOT NULL,
    response_signature JSON NOT NULL,
    field_mapping JSON NOT NULL,
    pagination_facts JSON NOT NULL,
    authentication_facts JSON NOT NULL,
    last_http_status SMALLINT UNSIGNED NULL,
    successful_probes INT UNSIGNED NOT NULL DEFAULT 0,
    failed_probes INT UNSIGNED NOT NULL DEFAULT 0,
    last_verified_at DATETIME(6) NULL,
    fresh_until DATETIME(6) NULL,
    created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    PRIMARY KEY (id),
    UNIQUE KEY uk_memory_endpoint (memory_id, endpoint_key),
    KEY idx_endpoint_family (endpoint_family, verified),
    KEY idx_endpoint_freshness (verified, fresh_until),
    CONSTRAINT fk_endpoint_memory FOREIGN KEY (memory_id) REFERENCES rag_memory(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS rag_failure_memory (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    failure_key BINARY(32) NOT NULL,
    domain VARCHAR(255) NOT NULL,
    route_template VARCHAR(512) NOT NULL DEFAULT '',
    route_hash BINARY(32) NOT NULL,
    task_type VARCHAR(64) NOT NULL,
    endpoint_family VARCHAR(255) NOT NULL DEFAULT '',
    root_error_type VARCHAR(64) NOT NULL,
    terminal_error_type VARCHAR(64) NOT NULL,
    error_category VARCHAR(64) NOT NULL,
    retry_strategy VARCHAR(64) NOT NULL,
    authentication_state VARCHAR(32) NOT NULL DEFAULT 'unknown',
    http_status SMALLINT UNSIGNED NULL,
    environment_fingerprint BINARY(32) NULL,
    evidence_summary TEXT NOT NULL,
    facts JSON NOT NULL,
    occurrence_count INT UNSIGNED NOT NULL DEFAULT 1,
    last_observed_at DATETIME(6) NOT NULL,
    block_until DATETIME(6) NULL,
    expires_at DATETIME(6) NULL,
    status VARCHAR(24) NOT NULL DEFAULT 'active',
    created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    PRIMARY KEY (id),
    UNIQUE KEY uk_failure_key (failure_key),
    KEY idx_failure_lookup (domain, task_type, root_error_type, status),
    KEY idx_failure_block (endpoint_family, block_until, status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS rag_execution (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    task_id VARCHAR(64) NOT NULL,
    domain VARCHAR(255) NOT NULL,
    route_template VARCHAR(512) NOT NULL DEFAULT '',
    task_type VARCHAR(64) NOT NULL,
    requested_fields JSON NOT NULL,
    canonical_fields JSON NOT NULL,
    authentication_state VARCHAR(32) NOT NULL DEFAULT 'unknown',
    final_status VARCHAR(32) NOT NULL,
    root_error_type VARCHAR(64) NOT NULL DEFAULT '',
    terminal_error_type VARCHAR(64) NOT NULL DEFAULT '',
    retry_strategy VARCHAR(64) NOT NULL DEFAULT '',
    items INT UNSIGNED NOT NULL DEFAULT 0,
    pagination_complete TINYINT(1) NOT NULL DEFAULT 0,
    selected_run VARCHAR(32) NOT NULL DEFAULT '',
    selected_strategy_id BIGINT UNSIGNED NULL,
    runtime_facts JSON NOT NULL,
    metrics JSON NOT NULL,
    supervisor_build VARCHAR(128) NOT NULL,
    browser_build VARCHAR(128) NOT NULL,
    code_build VARCHAR(128) NOT NULL,
    started_at DATETIME(6) NOT NULL,
    finished_at DATETIME(6) NOT NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uk_task_id (task_id),
    KEY idx_execution_domain (domain, task_type, finished_at),
    KEY idx_execution_status (final_status, finished_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS rag_memory_usage (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    execution_id BIGINT UNSIGNED NOT NULL,
    memory_id BIGINT UNSIGNED NOT NULL,
    agent_name VARCHAR(32) NOT NULL,
    stage VARCHAR(32) NOT NULL,
    usage_status VARCHAR(32) NOT NULL,
    rank_position SMALLINT UNSIGNED NULL,
    retrieval_score DECIMAL(8,6) NULL,
    validation_result VARCHAR(32) NOT NULL DEFAULT '',
    contribution_result VARCHAR(32) NOT NULL DEFAULT '',
    reason TEXT NOT NULL,
    details JSON NOT NULL,
    created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    PRIMARY KEY (id),
    KEY idx_usage_execution (execution_id),
    KEY idx_usage_memory (memory_id, usage_status),
    KEY idx_usage_feedback (memory_id, validation_result),
    CONSTRAINT fk_usage_execution FOREIGN KEY (execution_id) REFERENCES rag_execution(id) ON DELETE CASCADE,
    CONSTRAINT fk_usage_memory FOREIGN KEY (memory_id) REFERENCES rag_memory(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS rag_memory_event (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    task_id VARCHAR(64) NOT NULL,
    memory_id BIGINT UNSIGNED NULL,
    event_type VARCHAR(32) NOT NULL,
    agent_name VARCHAR(32) NOT NULL DEFAULT '',
    stage VARCHAR(32) NOT NULL DEFAULT '',
    details JSON NOT NULL,
    created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    PRIMARY KEY (id),
    KEY idx_event_task (task_id, created_at),
    KEY idx_event_memory (memory_id, event_type, created_at),
    CONSTRAINT fk_event_memory FOREIGN KEY (memory_id) REFERENCES rag_memory(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS rag_field_alias (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    canonical_field VARCHAR(64) NOT NULL,
    alias VARCHAR(128) NOT NULL,
    language VARCHAR(16) NOT NULL DEFAULT 'zh-CN',
    domain VARCHAR(255) NOT NULL DEFAULT '',
    priority SMALLINT NOT NULL DEFAULT 100,
    PRIMARY KEY (id),
    UNIQUE KEY uk_alias (alias, language, domain),
    KEY idx_canonical (canonical_field)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

INSERT IGNORE INTO rag_field_alias (canonical_field, alias, language, domain, priority) VALUES
('content','评论内容','zh-CN','',10),('content','评价内容','zh-CN','',10),('content','content','en','',10),
('author_name','评论用户','zh-CN','',10),('author_name','用户昵称','zh-CN','',10),('author_name','nickname','en','',10),
('created_at','评论时间','zh-CN','',10),('created_at','发布时间','zh-CN','',10),('created_at','creationTime','en','',10),
('like_count','点赞数','zh-CN','',10),('like_count','有用数','zh-CN','',10),('like_count','usefulVoteCount','en','',10);
